### ISSUE TITLE
Uncaught Error: length is not a number Exceeded connection limit for user

### ISSUE THREAD

**Issue by p-baleine** [p-baleine/atom-twitter-client#16]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.9.5
**Thrown From**: [atom-twitter-client](https://github.com/p-baleine/atom-twitter-client) package, v0.3.1
### Stack Trace

Uncaught Error: length is not a number Exceeded connection limit for user

```
At /Users/tajima-junpei/github/atom-twitter-client/lib/atom-twitter-timeline-view.coffee:20

Error: length is not a number Exceeded connection limit for user

    at TwitterStreamingClient.processData (/Users/tajima-junpei/github/atom-twitter-client/node_modules/twitter-streaming-client/lib/client.js:149:34)
    at Request.<anonymous> (/Users/tajima-junpei/github/atom-twitter-client/node_modules/twitter-streaming-client/lib/client.js:96:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:166:7)
    at IncomingMessage.<anonymous> (/Users/tajima-junpei/github/atom-twitter-client/node_modules/request/request.js:993:12)
    at emitOne (events.js:77:13)
    at IncomingMessage.emit (events.js:166:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at IncomingMessage.Readable.push (_stream_readable.js:109:10)
    at HTTPParser.parserOnBody (_http_common.js:109:22)
    at TLSSocket.socketOnData (_http_client.js:300:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:166:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at TLSSocket.Readable.push (_stream_readable.js:109:10)
    at TLSWrap.onread (net.js:517:20)
```
### Commands

```
     -2:17.1.0 command-palette:toggle (atom-text-editor.editor.is-focused.emacs-plus)
     -2:15.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:15 atom-twitter:home (atom-text-editor.editor.emacs-plus)
     -2:11 command-palette:toggle (atom-text-editor.editor.emacs-plus.is-focused)
  2x -2:09.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -2:08.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:08.9.0 atom-twitter:search (atom-text-editor.editor.emacs-plus)
     -2:07.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:01.1.0 tree-view:toggle (atom-text-editor.editor.emacs-plus.is-focused)
```
### Config

``` json
{
  "core": {},
  "atom-twitter-client": {
    "createInDevMode": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-twitter-client, v0.3.1
emacs-plus, v0.9.6

# Dev
No dev packages
```

**Comment by p-baleine** [comment]
The cause of this issue is in twitter-streaming-client.

https://github.com/p-baleine/twitter-streaming-client/issues/2
