### ISSUE TITLE
Uncaught ReferenceError: tweet is not defined

### ISSUE THREAD

**Issue by alugarius** [p-baleine/atom-twitter-client#25]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Debian GNU/Linux
**Thrown From**: [atom-twitter-client](https://github.com/p-baleine/atom-twitter-client) package 0.4.5

### Stack Trace

Uncaught ReferenceError: tweet is not defined

```
At /home/nox/.atom/packages/atom-twitter-client/node_modules/bluebird/js/main/promise.js:680

ReferenceError: tweet is not defined
    at /packages/atom-twitter-client/lib/atom-twitter-timeline-item-view.coffee:114:38
    at tryCatcher (/packages/atom-twitter-client/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/packages/atom-twitter-client/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/packages/atom-twitter-client/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/packages/atom-twitter-client/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/packages/atom-twitter-client/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/packages/atom-twitter-client/node_modules/bluebird/js/main/async.js:133:10)
    at MutationObserver.Async.drainQueues (/packages/atom-twitter-client/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

### Commands

```
     -2:31.7.0 core:confirm (input.hidden-input)
     -2:31.7.0 application:about (atom-pane.pane.active)
     -2:28.3.0 application:open-license (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:15.6.0 command-palette:toggle (ul.list-inline.tab-bar.inset-panel)
  3x -1:14.1.0 core:move-down (input.hidden-input)
     -1:13.5.0 core:move-up (input.hidden-input)
     -1:13.3.0 core:confirm (input.hidden-input)
     -1:13.3.0 atom-twitter:search (ul.list-inline.tab-bar.inset-panel)
     -1:10.8.0 core:confirm (input.hidden-input)
     -0:48.3.0 command-palette:toggle (atom-pane.pane.active)
  4x -0:44.4.0 core:backspace (input.hidden-input)
  2x -0:42.8.0 core:move-down (input.hidden-input)
     -0:42.3.0 core:confirm (input.hidden-input)
     -0:42.3.0 atom-twitter:search (atom-pane.pane.active)
  2x -0:25.8.0 core:backspace (input.hidden-input)
     -0:23.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.7 
atom-terminal-panel 4.4.4 
atom-twitter-client 0.4.5 
```

**Comment by alugarius** [comment]
i tried to Fav

**Comment by manzyun** [comment]
[IMHO] Append `@` on top `tweet` value.

# Append Point

## This line...
https://github.com/p-baleine/atom-twitter-client/blob/01cb691590d9dae86ed90b6ef7daffaef05db1ad/lib/atom-twitter-timeline-item-view.coffee#L98

## This line...
https://github.com/p-baleine/atom-twitter-client/blob/01cb691590d9dae86ed90b6ef7daffaef05db1ad/lib/atom-twitter-timeline-item-view.coffee#L107

## and... This line

https://github.com/p-baleine/atom-twitter-client/blob/01cb691590d9dae86ed90b6ef7daffaef05db1ad/lib/atom-twitter-timeline-item-view.coffee#L114

-------

Restart Atom Editor.  You can Fav and Retweet.
Works for me :roll_eyes:
